channels:
- conda-forge
- nodefaults
dependencies:
- astropy=6.0.1
- bilby=2.2.2
- corner=2.2.2
- dynesty=2.1.2
- gwosc=0.7.1
- gwpy=3.0.8
- h5py=3.11.0
- jupyter=1.0.0
- jupyter_client=8.6.1
- jupyter_console=6.6.3
- jupyter_core=5.7.2
- lalsuite=7.21
- ligo.skymap=1.1.2
- matplotlib=3.7.3
- notebook=7.1.2
- numpy=1.24.4
- pandas=2.2.2
- pip=24.0
- pycbc=2.4.0
- pygcn=1.0.2
- python=3.9.19
- scipy=1.9.3
- wget=1.21.4
- pesummary=1.2.0
- gwpopulation=0.10.0
name: igwn-py39-lw
